version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - /data/dev/aago_ranking/postgres/data:/var/lib/postgresql/data
      - /data/dev/aago_ranking/postgres/backup:/backups
    environment:
      - POSTGRES_USER=aago_ranking
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=aago_ranking
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres

